// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Waterblocks.Api.Infrastructure.Db;

#nullable disable

namespace Waterblocks.Api.Migrations
{
    [DbContext(typeof(FireblocksDbContext))]
    [Migration("20260115143355_RemoveTransactionEndpointFields")]
    partial class RemoveTransactionEndpointFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Waterblocks.Api.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressFormat")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AddressValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Bip44AddressIndex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerRefId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EnterpriseAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LegacyAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddressValue");

                    b.HasIndex("WalletId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Waterblocks.Api.Models.AdminSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Key");

                    b.ToTable("AdminSettings");
                });

            modelBuilder.Entity("Waterblocks.Api.Models.ApiKey", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("WorkspaceId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Waterblocks.Api.Models.Asset", b =>
                {
                    b.Property<string>("AssetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("BaseFee")
                        .HasColumnType("decimal(36,18)");

                    b.Property<int>("BlockchainType")
                        .HasColumnType("integer");

                    b.Property<string>("ContractAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Decimals")
                        .HasColumnType("integer");

                    b.Property<string>("FeeAssetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NativeAsset")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("AssetId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            AssetId = "BTC",
                            BaseFee = 0.0001m,
                            BlockchainType = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 15, 14, 33, 55, 3, DateTimeKind.Unspecified).AddTicks(281), new TimeSpan(0, 0, 0, 0, 0)),
                            Decimals = 8,
                            FeeAssetId = "BTC",
                            IsActive = true,
                            Name = "Bitcoin",
                            NativeAsset = "BTC",
                            Symbol = "BTC",
                            Type = "BASE_ASSET"
                        },
                        new
                        {
                            AssetId = "ETH",
                            BaseFee = 0.002m,
                            BlockchainType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 15, 14, 33, 55, 3, DateTimeKind.Unspecified).AddTicks(299), new TimeSpan(0, 0, 0, 0, 0)),
                            Decimals = 18,
                            FeeAssetId = "ETH",
                            IsActive = true,
                            Name = "Ethereum",
                            NativeAsset = "ETH",
                            Symbol = "ETH",
                            Type = "BASE_ASSET"
                        },
                        new
                        {
                            AssetId = "USDT",
                            BaseFee = 0.005m,
                            BlockchainType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 15, 14, 33, 55, 3, DateTimeKind.Unspecified).AddTicks(301), new TimeSpan(0, 0, 0, 0, 0)),
                            Decimals = 6,
                            FeeAssetId = "ETH",
                            IsActive = true,
                            Name = "Tether",
                            NativeAsset = "ETH",
                            Symbol = "USDT",
                            Type = "ERC20"
                        },
                        new
                        {
                            AssetId = "USDC",
                            BaseFee = 0.005m,
                            BlockchainType = 0,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 15, 14, 33, 55, 3, DateTimeKind.Unspecified).AddTicks(303), new TimeSpan(0, 0, 0, 0, 0)),
                            Decimals = 6,
                            FeeAssetId = "ETH",
                            IsActive = true,
                            Name = "USD Coin",
                            NativeAsset = "ETH",
                            Symbol = "USDC",
                            Type = "ERC20"
                        });
                });

            modelBuilder.Entity("Waterblocks.Api.Models.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(36,18)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Confirmations")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerRefId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DestinationTag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExternalTxId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(36,18)");

                    b.Property<string>("FeeCurrency")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Hash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean");

                    b.Property<decimal>("NetworkFee")
                        .HasColumnType("decimal(36,18)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReplacedByTxId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("decimal(36,18)");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("decimal(36,18)");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubStatus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TreatAsGrossAmount")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VaultAccountId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExternalTxId")
                        .IsUnique()
                        .HasFilter("\"ExternalTxId\" IS NOT NULL");

                    b.HasIndex("Hash");

                    b.HasIndex("State");

                    b.HasIndex("VaultAccountId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Waterblocks.Api.Models.VaultAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("AutoFuel")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerRefId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("HiddenOnUI")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerRefId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("VaultAccounts");
                });

            modelBuilder.Entity("Waterblocks.Api.Models.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(36,18)");

                    b.Property<string>("BlockHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BlockHeight")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Frozen")
                        .HasColumnType("decimal(36,18)");

                    b.Property<decimal>("LockedAmount")
                        .HasColumnType("decimal(36,18)");

                    b.Property<decimal>("Pending")
                        .HasColumnType("decimal(36,18)");

                    b.Property<decimal>("Staked")
                        .HasColumnType("decimal(36,18)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VaultAccountId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("VaultAccountId", "AssetId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Waterblocks.Api.Models.Workspace", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("Waterblocks.Api.Models.Address", b =>
                {
                    b.HasOne("Waterblocks.Api.Models.Wallet", "Wallet")
                        .WithMany("Addresses")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Waterblocks.Api.Models.ApiKey", b =>
                {
                    b.HasOne("Waterblocks.Api.Models.Workspace", "Workspace")
                        .WithMany("ApiKeys")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Waterblocks.Api.Models.Transaction", b =>
                {
                    b.HasOne("Waterblocks.Api.Models.VaultAccount", "VaultAccount")
                        .WithMany()
                        .HasForeignKey("VaultAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Waterblocks.Api.Models.Workspace", "Workspace")
                        .WithMany("Transactions")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaultAccount");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Waterblocks.Api.Models.VaultAccount", b =>
                {
                    b.HasOne("Waterblocks.Api.Models.Workspace", "Workspace")
                        .WithMany("VaultAccounts")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Waterblocks.Api.Models.Wallet", b =>
                {
                    b.HasOne("Waterblocks.Api.Models.VaultAccount", "VaultAccount")
                        .WithMany("Wallets")
                        .HasForeignKey("VaultAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaultAccount");
                });

            modelBuilder.Entity("Waterblocks.Api.Models.VaultAccount", b =>
                {
                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("Waterblocks.Api.Models.Wallet", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Waterblocks.Api.Models.Workspace", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Transactions");

                    b.Navigation("VaultAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
