apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "waterblocks.admin.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "waterblocks.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin-ui
data:
  API_BASE_URL: {{ include "waterblocks.admin.apiBaseUrl" . | quote }}
  ARCHIVE_ALL_WORKSPACES_ENABLED: {{ .Values.admin.config.archiveAllWorkspacesEnabled | quote }}
