apiVersion: v1
kind: Service
metadata:
  name: {{ include "waterblocks.admin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "waterblocks.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin-ui
spec:
  type: ClusterIP
  selector:
    {{- include "waterblocks.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: admin-ui
  ports:
    - name: http
      port: 80
      targetPort: http
