apiVersion: v1
kind: Service
metadata:
  name: {{ include "waterblocks.api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "waterblocks.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    {{- include "waterblocks.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8080
      targetPort: http
