// <auto-generated />
using System;
using FireblocksReplacement.Api.Infrastructure.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FireblocksReplacement.Api.Migrations
{
    [DbContext(typeof(FireblocksDbContext))]
    partial class FireblocksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FireblocksReplacement.Api.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddressValue");

                    b.HasIndex("WalletId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("FireblocksReplacement.Api.Models.Asset", b =>
                {
                    b.Property<string>("AssetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContractAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Decimals")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NativeAsset")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("AssetId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            AssetId = "BTC",
                            CreatedAt = new DateTime(2026, 1, 11, 6, 52, 45, 148, DateTimeKind.Utc).AddTicks(2060),
                            Decimals = 8,
                            IsActive = true,
                            Name = "Bitcoin",
                            NativeAsset = "BTC",
                            Symbol = "BTC",
                            Type = "BASE_ASSET"
                        },
                        new
                        {
                            AssetId = "ETH",
                            CreatedAt = new DateTime(2026, 1, 11, 6, 52, 45, 148, DateTimeKind.Utc).AddTicks(2060),
                            Decimals = 18,
                            IsActive = true,
                            Name = "Ethereum",
                            NativeAsset = "ETH",
                            Symbol = "ETH",
                            Type = "BASE_ASSET"
                        },
                        new
                        {
                            AssetId = "USDT",
                            CreatedAt = new DateTime(2026, 1, 11, 6, 52, 45, 148, DateTimeKind.Utc).AddTicks(2060),
                            Decimals = 6,
                            IsActive = true,
                            Name = "Tether",
                            NativeAsset = "ETH",
                            Symbol = "USDT",
                            Type = "ERC20"
                        },
                        new
                        {
                            AssetId = "USDC",
                            CreatedAt = new DateTime(2026, 1, 11, 6, 52, 45, 148, DateTimeKind.Utc).AddTicks(2070),
                            Decimals = 6,
                            IsActive = true,
                            Name = "USD Coin",
                            NativeAsset = "ETH",
                            Symbol = "USDC",
                            Type = "ERC20"
                        });
                });

            modelBuilder.Entity("FireblocksReplacement.Api.Models.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(36,18)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Confirmations")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DestinationTag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DestinationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DestinationVaultAccountId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(36,18)");

                    b.Property<string>("Hash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean");

                    b.Property<decimal>("NetworkFee")
                        .HasColumnType("decimal(36,18)");

                    b.Property<string>("ReplacedByTxId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SourceVaultAccountId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VaultAccountId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Hash");

                    b.HasIndex("State");

                    b.HasIndex("VaultAccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FireblocksReplacement.Api.Models.VaultAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("AutoFuel")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerRefId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("HiddenOnUI")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerRefId");

                    b.ToTable("VaultAccounts");
                });

            modelBuilder.Entity("FireblocksReplacement.Api.Models.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(36,18)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LockedAmount")
                        .HasColumnType("decimal(36,18)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VaultAccountId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("VaultAccountId", "AssetId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("FireblocksReplacement.Api.Models.Address", b =>
                {
                    b.HasOne("FireblocksReplacement.Api.Models.Wallet", "Wallet")
                        .WithMany("Addresses")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("FireblocksReplacement.Api.Models.Transaction", b =>
                {
                    b.HasOne("FireblocksReplacement.Api.Models.VaultAccount", "VaultAccount")
                        .WithMany()
                        .HasForeignKey("VaultAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaultAccount");
                });

            modelBuilder.Entity("FireblocksReplacement.Api.Models.Wallet", b =>
                {
                    b.HasOne("FireblocksReplacement.Api.Models.VaultAccount", "VaultAccount")
                        .WithMany("Wallets")
                        .HasForeignKey("VaultAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaultAccount");
                });

            modelBuilder.Entity("FireblocksReplacement.Api.Models.VaultAccount", b =>
                {
                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("FireblocksReplacement.Api.Models.Wallet", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
